INSERT INTO GF_ROLDIR (RDI_ROL)
VALUES ('President');
INSERT INTO GF_ROLDIR (RDI_ROL)
VALUES ('Vicepresident I');
INSERT INTO GF_ROLDIR (RDI_ROL)
VALUES ('Secretari');
INSERT INTO GF_ROLDIR (RDI_ROL)
VALUES ('Tresorer');
INSERT INTO GF_ROLDIR (RDI_ROL)
VALUES ('Vocal');

INSERT INTO GF_CONFIG (CONF_ID, CONF_CIF, CONF_NOM, CONF_COL, CONF_CLF1, CONF_CLF2)
VALUES (1, 'G57861692', 'Athletic Club Montuiri', '#000000', '#ee4f4f', '#e8d1d1');

INSERT INTO GF_CAMPANYA (CAM_ANY, CAM_TITOL) VALUES ('2025-01-01', 'Campanya 2025-2026');

INSERT INTO GF_TIPSOCI (TIS_CAM, TIS_NOM, TIS_IMP) VALUES (1, 'Tipo Soci 1', 50);
INSERT INTO GF_TIPSOCI (TIS_CAM, TIS_NOM, TIS_IMP) VALUES (1, 'Tipo Soci 2', 75);
