INSERT INTO GF_ROLDIR (RDI_ROL)
VALUES ('President');
INSERT INTO GF_ROLDIR (RDI_ROL)
VALUES ('Vicepresident I');
INSERT INTO GF_ROLDIR (RDI_ROL)
VALUES ('Secretari');
INSERT INTO GF_ROLDIR (RDI_ROL)
VALUES ('Tresorer');
INSERT INTO GF_ROLDIR (RDI_ROL)
VALUES ('Vocal');

INSERT INTO GF_CONFIG (CONF_ID, CONF_CIF, CONF_NOM, CONF_COL, CONF_CLF1, CONF_CLF2)
VALUES (1, 'G57861692', 'Athletic Club Montuiri', '#000000', '#ee4f4f', '#e8d1d1');

INSERT INTO GF_CAMPANYA (CAM_ANY, CAM_TITOL) VALUES ('2025-01-01', 'Temporada 2025-2026');

INSERT INTO GF_TIPSOCI (TIS_CAM, TIS_NOM, TIS_IMP) VALUES (1, 'Tipo Soci 1', 50);
INSERT INTO GF_TIPSOCI (TIS_CAM, TIS_NOM, TIS_IMP) VALUES (1, 'Tipo Soci 2', 75);

INSERT INTO GF_MENSUALITAT (MEN_ANY, MEN_MES, MEN_CAM) VALUES (2026, 12, 1);
INSERT INTO GF_MENSUALITAT (MEN_ANY, MEN_MES, MEN_CAM) VALUES (2026, 11, 1);
INSERT INTO GF_MENSUALITAT (MEN_ANY, MEN_MES, MEN_CAM) VALUES (2026, 10, 1);
INSERT INTO GF_MENSUALITAT (MEN_ANY, MEN_MES, MEN_CAM) VALUES (2026, 9, 1);
INSERT INTO GF_MENSUALITAT (MEN_ANY, MEN_MES, MEN_CAM) VALUES (2026, 8, 1);
INSERT INTO GF_MENSUALITAT (MEN_ANY, MEN_MES, MEN_CAM) VALUES (2026, 7, 1);
INSERT INTO GF_MENSUALITAT (MEN_ANY, MEN_MES, MEN_CAM) VALUES (2027, 6, 1);
INSERT INTO GF_MENSUALITAT (MEN_ANY, MEN_MES, MEN_CAM) VALUES (2027, 5, 1);
INSERT INTO GF_MENSUALITAT (MEN_ANY, MEN_MES, MEN_CAM) VALUES (2027, 4, 1);
INSERT INTO GF_MENSUALITAT (MEN_ANY, MEN_MES, MEN_CAM) VALUES (2027, 3, 1);
INSERT INTO GF_MENSUALITAT (MEN_ANY, MEN_MES, MEN_CAM) VALUES (2027, 2, 1);
INSERT INTO GF_MENSUALITAT (MEN_ANY, MEN_MES, MEN_CAM) VALUES (2027, 1, 1);
-- Script de inserción de jugadores con licencia tipo A compatible con H2
-- Generado automáticamente el 2025-09-09
-- Inserciones en GF_MEMPLANT y GF_JUGADOR respetando la herencia
-- MEM_ID se autogenera, se usa subconsulta para obtener el último ID

-- Inicio de inserciones
INSERT INTO GF_MEMPLANT (MEM_CAM, MEM_NOM, MEM_LLIN1, MEM_LLIN2, MEM_DNAIX, MEM_ROL) VALUES (1, 'ANTONI', 'LLULL', 'PLOMER', '2002-07-19', 'GF_JUGADOR');
INSERT INTO GF_JUGADOR (MEM_ID, JUG_POSICIO) VALUES ((SELECT MAX(MEM_ID) FROM GF_MEMPLANT), 'DAVANTER');
INSERT INTO GF_MEMPLANT (MEM_CAM, MEM_NOM, MEM_LLIN1, MEM_LLIN2, MEM_DNAIX, MEM_ROL) VALUES (1, 'RAFEL', 'MAGRO', 'PERELLO', '2002-01-31', 'GF_JUGADOR');
INSERT INTO GF_JUGADOR (MEM_ID, JUG_POSICIO) VALUES ((SELECT MAX(MEM_ID) FROM GF_MEMPLANT), 'DAVANTER');
INSERT INTO GF_MEMPLANT (MEM_CAM, MEM_NOM, MEM_LLIN1, MEM_LLIN2, MEM_DNAIX, MEM_ROL) VALUES (1, 'JOAN', 'MANERA', 'GARAU', '2002-07-15', 'GF_JUGADOR');
INSERT INTO GF_JUGADOR (MEM_ID, JUG_POSICIO) VALUES ((SELECT MAX(MEM_ID) FROM GF_MEMPLANT), 'MIGCAMPISTA');
INSERT INTO GF_MEMPLANT (MEM_CAM, MEM_NOM, MEM_LLIN1, MEM_LLIN2, MEM_DNAIX, MEM_ROL) VALUES (1, 'JOSE LUIS', 'PUIGSERVER', 'TOLENTINO', '2006-09-29', 'GF_JUGADOR');
INSERT INTO GF_JUGADOR (MEM_ID, JUG_POSICIO) VALUES ((SELECT MAX(MEM_ID) FROM GF_MEMPLANT), 'MIGCAMPISTA');
INSERT INTO GF_MEMPLANT (MEM_CAM, MEM_NOM, MEM_LLIN1, MEM_LLIN2, MEM_DNAIX, MEM_ROL) VALUES (1, 'MARC', 'SANSÓ', 'SANCHEZ', '2005-09-25', 'GF_JUGADOR');
INSERT INTO GF_JUGADOR (MEM_ID, JUG_POSICIO) VALUES ((SELECT MAX(MEM_ID) FROM GF_MEMPLANT), 'DEFENSA');
INSERT INTO GF_MEMPLANT (MEM_CAM, MEM_NOM, MEM_LLIN1, MEM_LLIN2, MEM_DNAIX, MEM_ROL) VALUES (1, 'DIDAC', 'FARRERAS', 'SERRAT', '1998-09-16', 'GF_JUGADOR');
INSERT INTO GF_JUGADOR (MEM_ID, JUG_POSICIO) VALUES ((SELECT MAX(MEM_ID) FROM GF_MEMPLANT), 'MIGCAMPISTA');
INSERT INTO GF_MEMPLANT (MEM_CAM, MEM_NOM, MEM_LLIN1, MEM_LLIN2, MEM_DNAIX, MEM_ROL) VALUES (1, 'MIGUEL A', 'ALVAREZ', 'GONZALEZ', '1985-12-06', 'GF_JUGADOR');
INSERT INTO GF_JUGADOR (MEM_ID, JUG_POSICIO) VALUES ((SELECT MAX(MEM_ID) FROM GF_MEMPLANT), 'DEFENSA');
INSERT INTO GF_MEMPLANT (MEM_CAM, MEM_NOM, MEM_LLIN1, MEM_LLIN2, MEM_DNAIX, MEM_ROL) VALUES (1, 'MIQUEL', 'BAUZA', 'BARCELO', '1998-02-19', 'GF_JUGADOR');
INSERT INTO GF_JUGADOR (MEM_ID, JUG_POSICIO) VALUES ((SELECT MAX(MEM_ID) FROM GF_MEMPLANT), 'MIGCAMPISTA');
INSERT INTO GF_MEMPLANT (MEM_CAM, MEM_NOM, MEM_LLIN1, MEM_LLIN2, MEM_DNAIX, MEM_ROL) VALUES (1, 'JOSEP', 'BAUZA', 'POCOVI', '2002-05-28', 'GF_JUGADOR');
INSERT INTO GF_JUGADOR (MEM_ID, JUG_POSICIO) VALUES ((SELECT MAX(MEM_ID) FROM GF_MEMPLANT), 'MIGCAMPISTA');
INSERT INTO GF_MEMPLANT (MEM_CAM, MEM_NOM, MEM_LLIN1, MEM_LLIN2, MEM_DNAIX, MEM_ROL) VALUES (1, 'JOSE', 'CASTIZO', 'GIL', '1993-01-14', 'GF_JUGADOR');
INSERT INTO GF_JUGADOR (MEM_ID, JUG_POSICIO) VALUES ((SELECT MAX(MEM_ID) FROM GF_MEMPLANT), 'DEFENSA');
INSERT INTO GF_MEMPLANT (MEM_CAM, MEM_NOM, MEM_LLIN1, MEM_LLIN2, MEM_DNAIX, MEM_ROL) VALUES (1, 'SERGIO', 'CAVA', 'MATIES', '2005-09-26', 'GF_JUGADOR');
INSERT INTO GF_JUGADOR (MEM_ID, JUG_POSICIO) VALUES ((SELECT MAX(MEM_ID) FROM GF_MEMPLANT), 'DAVANTER');
INSERT INTO GF_MEMPLANT (MEM_CAM, MEM_NOM, MEM_LLIN1, MEM_LLIN2, MEM_DNAIX, MEM_ROL) VALUES (1, 'BALTASAR', 'CERDA', 'GARCIAS', '2000-01-31', 'GF_JUGADOR');
INSERT INTO GF_JUGADOR (MEM_ID, JUG_POSICIO) VALUES ((SELECT MAX(MEM_ID) FROM GF_MEMPLANT), 'DEFENSA');
INSERT INTO GF_MEMPLANT (MEM_CAM, MEM_NOM, MEM_LLIN1, MEM_LLIN2, MEM_DNAIX, MEM_ROL) VALUES (1, 'MIQUEL', 'FLORIT', 'RIGO', '2000-02-09', 'GF_JUGADOR');
INSERT INTO GF_JUGADOR (MEM_ID, JUG_POSICIO) VALUES ((SELECT MAX(MEM_ID) FROM GF_MEMPLANT), 'DAVANTER');
INSERT INTO GF_MEMPLANT (MEM_CAM, MEM_NOM, MEM_LLIN1, MEM_LLIN2, MEM_DNAIX, MEM_ROL) VALUES (1, 'MIQUEL', 'GINARD', 'FIOL', '1994-11-05', 'GF_JUGADOR');
INSERT INTO GF_JUGADOR (MEM_ID, JUG_POSICIO) VALUES ((SELECT MAX(MEM_ID) FROM GF_MEMPLANT), 'DAVANTER');
INSERT INTO GF_MEMPLANT (MEM_CAM, MEM_NOM, MEM_LLIN1, MEM_LLIN2, MEM_DNAIX, MEM_ROL) VALUES (1, 'MIQUEL', 'MARTORELL', 'BAUZA', '2001-05-09', 'GF_JUGADOR');
INSERT INTO GF_JUGADOR (MEM_ID, JUG_POSICIO) VALUES ((SELECT MAX(MEM_ID) FROM GF_MEMPLANT), 'DEFENSA');
INSERT INTO GF_MEMPLANT (MEM_CAM, MEM_NOM, MEM_LLIN1, MEM_LLIN2, MEM_DNAIX, MEM_ROL) VALUES (1, 'PERE J', 'MARTORELL', 'BAUZA', '1997-01-23', 'GF_JUGADOR');
INSERT INTO GF_JUGADOR (MEM_ID, JUG_POSICIO) VALUES ((SELECT MAX(MEM_ID) FROM GF_MEMPLANT), 'DEFENSA');
INSERT INTO GF_MEMPLANT (MEM_CAM, MEM_NOM, MEM_LLIN1, MEM_LLIN2, MEM_DNAIX, MEM_ROL) VALUES (1, 'GUILLERMO', 'MAS', 'JAUME', '2001-06-10', 'GF_JUGADOR');
INSERT INTO GF_JUGADOR (MEM_ID, JUG_POSICIO) VALUES ((SELECT MAX(MEM_ID) FROM GF_MEMPLANT), 'DEFENSA');
INSERT INTO GF_MEMPLANT (MEM_CAM, MEM_NOM, MEM_LLIN1, MEM_LLIN2, MEM_DNAIX, MEM_ROL) VALUES (1, 'ANTONI', 'MAYOL', 'ARBONA', '1992-02-27', 'GF_JUGADOR');
INSERT INTO GF_JUGADOR (MEM_ID, JUG_POSICIO) VALUES ((SELECT MAX(MEM_ID) FROM GF_MEMPLANT), 'MIGCAMPISTA');
INSERT INTO GF_MEMPLANT (MEM_CAM, MEM_NOM, MEM_LLIN1, MEM_LLIN2, MEM_DNAIX, MEM_ROL) VALUES (1, 'BENET RAMON', 'MOLL', 'CAMPINS', '2000-10-06', 'GF_JUGADOR');
INSERT INTO GF_JUGADOR (MEM_ID, JUG_POSICIO) VALUES ((SELECT MAX(MEM_ID) FROM GF_MEMPLANT), 'PORTER');
INSERT INTO GF_MEMPLANT (MEM_CAM, MEM_NOM, MEM_LLIN1, MEM_LLIN2, MEM_DNAIX, MEM_ROL) VALUES (1, 'MIQUEL', 'SAMANIEGO', 'ANDREU', '2004-02-23', 'GF_JUGADOR');
INSERT INTO GF_JUGADOR (MEM_ID, JUG_POSICIO) VALUES ((SELECT MAX(MEM_ID) FROM GF_MEMPLANT), 'DEFENSA');
INSERT INTO GF_MEMPLANT (MEM_CAM, MEM_NOM, MEM_LLIN1, MEM_LLIN2, MEM_DNAIX, MEM_ROL) VALUES (1, 'BARTOMEU', 'SASTRE', 'MULET', '1994-09-27', 'GF_JUGADOR');
INSERT INTO GF_JUGADOR (MEM_ID, JUG_POSICIO) VALUES ((SELECT MAX(MEM_ID) FROM GF_MEMPLANT), 'MIGCAMPISTA');
INSERT INTO GF_MEMPLANT (MEM_CAM, MEM_NOM, MEM_LLIN1, MEM_LLIN2, MEM_DNAIX, MEM_ROL) VALUES (1, 'RACHID', 'ZOUGGAGHI', 'ZOUGGAGH', '1997-08-24', 'GF_JUGADOR');
INSERT INTO GF_JUGADOR (MEM_ID, JUG_POSICIO) VALUES ((SELECT MAX(MEM_ID) FROM GF_MEMPLANT), 'PORTER');
-- Fin del script
