CREATE TABLE GF_CAMPANYA
(
    CAM_ID     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CAM_ANY    date                                    NOT NULL,
    CAM_IMPORT BIGINT                                  NOT NULL,
    CAM_TITOL  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_gf_campanya PRIMARY KEY (CAM_ID)
);


CREATE TABLE GF_PATROCINADOR
(
    PAT_ID      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    PAT_CAM     BIGINT                                  NOT NULL,
    PAT_CIF     VARCHAR(255)                            NOT NULL,
    PAT_NOM     VARCHAR(255)                            NOT NULL,
    PAT_DONACIO BIGINT                                  NOT NULL,
    PAT_DATADON date                                    NOT NULL,
    CONSTRAINT pk_gf_patrocinador PRIMARY KEY (PAT_ID)
);

CREATE TABLE GF_SOCI
(
    SOC_ID     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    SOC_CAM    BIGINT                                  NOT NULL,
    SOC_ESTPAG VARCHAR(1)                              NOT NULL,
    SOC_NOM    VARCHAR(255)                            NOT NULL,
    SOC_LLIN1  VARCHAR(255),
    SOC_LLIN2  VARCHAR(255),
    SOC_PATROC BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_gf_soci PRIMARY KEY (SOC_ID)
);

ALTER TABLE GF_SOCI
    ADD CONSTRAINT FK_GF_SOCI_ON_SOC_CAM FOREIGN KEY (SOC_CAM) REFERENCES GF_CAMPANYA (CAM_ID);

ALTER TABLE GF_PATROCINADOR
    ADD CONSTRAINT FK_GF_PATROCINADOR_ON_PAT_CAM FOREIGN KEY (PAT_CAM) REFERENCES GF_CAMPANYA (CAM_ID);