INSERT INTO GF_CATDESPESA (CDE_NOM) VALUES ('Competició i Federació');
INSERT INTO GF_CATDESPESA (CDE_NOM) VALUES ('Personal i Serveis Professionals');
INSERT INTO GF_CATDESPESA (CDE_NOM) VALUES ('Material Esportiu i Equipament');
INSERT INTO GF_CATDESPESA (CDE_NOM) VALUES ('Administració i Gestió');
INSERT INTO GF_CATDESPESA (CDE_NOM) VALUES ('Salut i Farmàcia');
INSERT INTO GF_CATDESPESA (CDE_NOM) VALUES ('Activitat Social');
INSERT INTO GF_CATDESPESA (CDE_NOM) VALUES ('Protocol i Representació');
INSERT INTO GF_CATDESPESA (CDE_NOM) VALUES ('Altres');