ALTER TABLE GF_EQUIP
    ADD COLUMN IF NOT EXISTS EQP_QUOTA NUMERIC(10,2);

CREATE TABLE GF_POS_JUGADOR
(
    POS_ID  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    POS_NOM VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_gf_pos_jugador PRIMARY KEY (POS_ID)
);

-- Índice único por nombre (evita duplicados por mayúsculas/minúsculas si procede)
-- Si quieres colación case-insensitive, usa citext o LOWER(POS_NOM) con índice funcional
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = current_schema()
          AND indexname = 'ux_pos_jugador_pos_nom'
    ) THEN
        EXECUTE 'CREATE UNIQUE INDEX ux_pos_jugador_pos_nom ON GF_POS_JUGADOR (POS_NOM)';
END IF;
END $$;
---
-- 1) Sembrar catálogo desde los valores actuales (si todavía no están)
--    Inserta los distintos valores del enum string que ya existan en GF_JUGADOR
INSERT INTO GF_POS_JUGADOR (POS_NOM)
SELECT DISTINCT JUG_POSICIO
FROM GF_JUGADOR
WHERE JUG_POSICIO IS NOT NULL
  AND NOT EXISTS (
        SELECT 1 FROM GF_POS_JUGADOR p WHERE p.POS_NOM = GF_JUGADOR.JUG_POSICIO
    );

-- 2) Añadir la nueva columna FK (temporal) en GF_JUGADOR
ALTER TABLE GF_JUGADOR
    ADD COLUMN IF NOT EXISTS JUG_POSICIO_ID BIGINT;

-- 3) Migrar datos: mapear el texto a su POS_ID
UPDATE GF_JUGADOR j
SET JUG_POSICIO_ID = p.POS_ID
    FROM GF_POS_JUGADOR p
WHERE p.POS_NOM = j.JUG_POSICIO
  AND j.JUG_POSICIO IS NOT NULL;

-- 4) Validar que no quedan nulos (si los hubiera, decide cómo proceder)
--    Aquí forzamos NOT NULL porque en la entidad nueva es optional=false
ALTER TABLE GF_JUGADOR
    ALTER COLUMN JUG_POSICIO_ID SET NOT NULL;

-- 5) Crear FK con ON DELETE RESTRICT (o CASCADE si negocio lo requiere)
--    Para catálogos, lo normal es RESTRICT para proteger integridad referencial.
ALTER TABLE GF_JUGADOR
    ADD CONSTRAINT FK_JUGADOR_POSICIO
        FOREIGN KEY (JUG_POSICIO_ID) REFERENCES GF_POS_JUGADOR(POS_ID)
            ON UPDATE CASCADE
            ON DELETE RESTRICT;

-- Índice para rendimiento de la FK
CREATE INDEX IF NOT EXISTS IX_JUGADOR_POSICIO_ID ON GF_JUGADOR(JUG_POSICIO_ID);

-- 6) Retirar la columna antigua de texto y renombrar la nueva al nombre esperado por JPA
ALTER TABLE GF_JUGADOR
DROP COLUMN IF EXISTS JUG_POSICIO;

---
ALTER TABLE GF_JUGADOR
    RENAME COLUMN JUG_POSICIO_ID TO JUG_POSICIO;


ALTER TABLE GF_CONTACTE
    ADD COLUMN IF NOT EXISTS CPR_MEM BIGINT;


DO $$
DECLARE
fkname text;
BEGIN
SELECT c.conname INTO fkname
FROM pg_constraint c
         JOIN pg_class t ON t.oid = c.conrelid
WHERE t.relname = 'gf_contacteprov'
  AND c.contype = 'f';
IF fkname IS NOT NULL THEN
        EXECUTE 'ALTER TABLE GF_CONTACTEPROV DROP CONSTRAINT ' || quote_ident(fkname);
END IF;
END $$;

-- 4) Crear FK con ON UPDATE CASCADE y ON DELETE SET NULL (no borra contactos usados por otros módulos)
ALTER TABLE GF_CONTACTEPROV
    ADD CONSTRAINT FK_CONTACTEPROV_MEMBRE
        FOREIGN KEY (CPR_MEM) REFERENCES GF_MEMPLANT(MEM_ID)
            ON UPDATE CASCADE
            ON DELETE SET NULL;
---


CREATE TABLE GF_QUOTA_JUGADOR
(
    QUO_ID    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    QUO_JUG   BIGINT                                  NOT NULL,
    QUO_DATA  TIMESTAMP WITHOUT TIME ZONE,
    QUO_ESTAT VARCHAR(255)                            NOT NULL,
    QUO_EXEP  BOOLEAN,
    QUO_QUANT DECIMAL,
    CONSTRAINT pk_gf_quota_jugador PRIMARY KEY (QUO_ID)
);

ALTER TABLE GF_QUOTA_JUGADOR
    ADD CONSTRAINT FK_GF_QUOTA_JUGADOR_ON_QUO_JUG FOREIGN KEY (QUO_JUG) REFERENCES GF_JUGADOR (MEM_ID);