CREATE TABLE GF_PLANTILLA_DOCUMENTO
(
    PLA_ID   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    PLA_COD  VARCHAR(100)                            NOT NULL,
    PLA_NOM  VARCHAR(255)                            NOT NULL,
    PLA_IDI  VARCHAR(255)                            NOT NULL,
    PLA_HTML TEXT                                    NOT NULL,
    PLA_CSS  TEXT,
    PLA_CREA TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    PLA_ACT  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_gf_plantilla_documento PRIMARY KEY (PLA_ID)
);